services:
  - type: web
    name: bepu-ai-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: OPENAI_MODEL
        value: "gpt-4o-mini"
      - key: BF_TEMPERATURE
        value: "0.6"
      - key: BF_APP_VERSION
        value: "A1-3-2025-08-27"
      # - key: OPENAI_API_KEY
      #   sync: false
